version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    profiles:
      - dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
